Improve clean-ubuntu

diff --git a/bin/clean-ubuntu b/bin/clean-ubuntu
--- a/bin/clean-ubuntu
+++ b/bin/clean-ubuntu
@@ -1,58 +1,137 @@
-#!/bin/sh
+#!/usr/bin/env bash
+# -*- coding: utf-8 -*-
+# vim: set ft=sh et ts=4 sw=4 sts=4:
 
-# Free up disk space on Ubuntu - clean log, cache, archive packages/apt archives,
+# INFO
+# --------------------------------------------------------------------------------------
+# Free up disk space on Debian, Ubuntu - clean log, cache, archive packages/apt archives,
 # orphaned packages, old kernel and remove the trash
+#
 # Gist repo:
 # https://gist.github.com/SerhatTeker/1a6c6c49b58ed5531156bece4c666994
 # Upstream fork:
 # https://gist.github.com/Iman/8c4605b2b3ce8226b08a
 
-echo "Cleaning is started"
+# USAGE
+# --------------------------------------------------------------------------------------
+# $ curl -fsSL https://gist.githubusercontent.com/SerhatTeker/52274925dd75c3ea03a0fd4a04f47e9f/raw/clean-ubuntu | sudo bash
+# or
+# $ wget -O - https://gist.githubusercontent.com/SerhatTeker/52274925dd75c3ea03a0fd4a04f47e9f/raw/clean-ubuntu | sudo bash
+
+
+# Bash safeties: exit on error, no unset variables, pipelines can't hide errors
+set -o errexit
+set -o nounset
+set -o pipefail
+
+
+_is_linux() {
+    local uname="$(uname -a)"
+
+    if [[ ! "$uname" =~ Linux ]]; then
+		echo "Not Linux OS!"
+        exit
+    fi
+}
+
+# Ensure running as root
+check_is_sudo() {
+	if [ "$EUID" -ne 0 ]; then
+		echo "Please run as root!"
+		exit
+	fi
+}
+
 
 # Check the Drive Space Used by Cached Files
-sudo du -sh /var/cache/apt/archives
+_apt_archive() {
+    sudo du -sh /var/cache/apt/archives
+}
 
 # Clean all the log file
 # for logs in `find /var/log -type f`;  do > $logs; done
-
-logs=`sudo find /var/log -type f`
-for i in $logs
-do
-> $i
-done
+_logs() {
+    logs=`sudo find /var/log -type f`
+    for i in $logs
+    do
+    > $i
+    done
+}
 
 # Getting rid of partial packages
-sudo apt-get clean && sudo apt-get autoclean
+_partial() {
+    sudo apt-get clean && sudo apt-get autoclean
+}
+
 # Commented out
 # To avoid harming your system by removing key packages
-# apt-get remove --purge -y software-properties-common
+_software_common() {
+    # apt-get remove --purge -y software-properties-common
+    :
+}
 
 # Getting rid of no longer required packages
-sudo apt-get autoremove -y
+_auto_remove() {
+    sudo apt-get autoremove -y
+}
 
 # Getting rid of orphaned packages
-deborphan | xargs sudo apt-get -y remove --purge
+_orphan() {
+    deborphan | xargs sudo apt-get -y remove --purge
+}
 
 # Free up space by clean out the cached packages
-sudo apt-get clean
+_cached_packages() {
+    sudo apt-get clean
+}
 
 # Remove the Trash
-rm -rf /home/*/.local/share/Trash/*/**
-rm -rf /root/.local/share/Trash/*/**
+_thrash() {
+    sudo rm -rf /home/*/.local/share/Trash/*/**
+    sudo rm -rf /root/.local/share/Trash/*/**
+}
 
 # Remove Man
-sudo rm -rf /usr/share/man/??
-sudo rm -rf /usr/share/man/??_*
+_man() {
+    sudo rm -rf /usr/share/man/??
+    sudo rm -rf /usr/share/man/??_*
+}
 
 # Delete all .gz and rotated file
-sudo find /var/log -type f -regex ".*\.gz$" | xargs rm -Rf
-sudo find /var/log -type f -regex ".*\.[0-9]$" | xargs rm -Rf
+_rotated() {
+    sudo find /var/log -type f -regex ".*\.gz$" | xargs rm -Rf
+    sudo find /var/log -type f -regex ".*\.[0-9]$" | xargs rm -Rf
+}
 
 # Cleaning the old kernels
-sudo dpkg-query -l | grep linux-im*
-# dpkg-query -l |grep linux-im*|awk '{print $2}'
-sudo apt-get purge $(dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | head -n -1) --assume-yes
-sudo apt-get install linux-headers-`uname -r|cut -d'-' -f3`-`uname -r|cut -d'-' -f4`
+_kernels() {
+    sudo dpkg-query -l | grep linux-im*
+    # dpkg-query -l |grep linux-im*|awk '{print $2}'
+    sudo apt-get purge \
+        $(dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | head -n -1) \
+        --assume-yes
+    sudo apt-get install linux-headers-`uname -r|cut -d'-' -f3`-`uname -r|cut -d'-' -f4`
+}
 
-# Cleaning is completed
-echo "Cleaning is completed"
+
+main() {
+    _is_linux
+    check_is_sudo
+    echo "Cleaning is started"
+    _apt_archive
+    _logs
+    _partial
+    _software_common
+    _auto_remove
+    _orphan
+    _cached_packages
+    _thrash
+    _man
+    _rotated
+    _kernels
+    echo "Cleaning is completed"
+}
+
+main
+
+exit 0
