Fix genpasswd bin

diff --git a/bin/utils/genpasswd b/bin/utils/genpasswd
--- a/bin/utils/genpasswd
+++ b/bin/utils/genpasswd
@@ -1,5 +1,15 @@
-#! /bin/bash
+#!/usr/bin/env bash
+# -*- coding: utf-8 -*-
+# vim: set ft=sh et ts=4 sw=4 sts=4:
+
 # Generate pseudorandom password
+
+
+# Bash safeties: exit on error, no unset variables, pipelines can't hide errors
+set -o errexit
+set -o nounset
+set -o pipefail
+
 
 # Default length
 LENGTH=20
